// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiImport
    {
        public TblItiImport()
        {
            TblItiBookdetails = new HashSet<TblItiBookdetails>();
            TblItiImportDetails = new HashSet<TblItiImportDetails>();
        }

        public int ImpId { get; set; }
        public DateTime? ImpDate { get; set; }
        public int? SupId { get; set; }
        public int? UseDelId { get; set; }
        public DateTime? UseEditDate { get; set; }

        public virtual TblItiSupplyer Sup { get; set; }
        public virtual TblUseLogintime UseDel { get; set; }
        public virtual ICollection<TblItiBookdetails> TblItiBookdetails { get; set; }
        public virtual ICollection<TblItiImportDetails> TblItiImportDetails { get; set; }
    }
}