// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiPosition
    {
        public TblItiPosition()
        {
            TblItiEmployee = new HashSet<TblItiEmployee>();
            TblItiStudent = new HashSet<TblItiStudent>();
        }

        public int PosId { get; set; }
        public string PosNameKh { get; set; }
        public string PosNameEn { get; set; }

        public virtual ICollection<TblItiEmployee> TblItiEmployee { get; set; }
        public virtual ICollection<TblItiStudent> TblItiStudent { get; set; }
    }
}