// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiReturnReadDetails
    {
        public int RetDelReadId { get; set; }
        public int? RetReadId { get; set; }
        public int? ReadDelId { get; set; }
        public int? StatusId { get; set; }

        public virtual TblItiReadDetails ReadDel { get; set; }
        public virtual TblReturnRead RetRead { get; set; }
        public virtual TblItiStatus Status { get; set; }
    }
}