// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiBorrow
    {
        public TblItiBorrow()
        {
            TblBorrowDetails = new HashSet<TblBorrowDetails>();
            TblItiReturndeltails = new HashSet<TblItiReturndeltails>();
        }

        public int BorId { get; set; }
        public int? StuId { get; set; }
        public int? UseDelId { get; set; }
        public DateTime? UseEditDate { get; set; }
        public DateTime? BorStartDate { get; set; }
        public DateTime? BorEndDate { get; set; }
        public string BorCode { get; set; }
        public bool? IsRequired { get; set; }

        public virtual TblItiStudent Stu { get; set; }
        public virtual TblUseLogintime UseDel { get; set; }
        public virtual ICollection<TblBorrowDetails> TblBorrowDetails { get; set; }
        public virtual ICollection<TblItiReturndeltails> TblItiReturndeltails { get; set; }
    }
}