// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiRead
    {
        public TblItiRead()
        {
            TblItiReadDetails = new HashSet<TblItiReadDetails>();
        }

        public int ReadId { get; set; }
        public DateTime? ReadDate { get; set; }
        public int? UseDelId { get; set; }
        public DateTime? UseEditDate { get; set; }
        public int? StuId { get; set; }
        public short? TimeTypeId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public bool? IsReturn { get; set; }
        public int? StatusId { get; set; }

        public virtual TblTimeType TimeType { get; set; }
        public virtual TblUseLogintime UseDel { get; set; }
        public virtual ICollection<TblItiReadDetails> TblItiReadDetails { get; set; }
    }
}