// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiReturndeltails
    {
        public int RetDelId { get; set; }
        public int? RetId { get; set; }
        public int? StatusId { get; set; }
        public int? BorId { get; set; }

        public virtual TblItiBorrow Bor { get; set; }
        public virtual TblItiReturn Ret { get; set; }
    }
}