// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiEmployee
    {
        public TblItiEmployee()
        {
            TblItiUser = new HashSet<TblItiUser>();
        }

        public int EmpId { get; set; }
        public string EmpNoteId { get; set; }
        public string EmpNameKh { get; set; }
        public string EmpSex { get; set; }
        public DateTime? EmpDob { get; set; }
        public string EmpAddress { get; set; }
        public DateTime? EmpDateIn { get; set; }
        public DateTime? EmpDateOut { get; set; }
        public string EmpPhone { get; set; }
        public bool? EmpAtive { get; set; }
        public int? PosId { get; set; }
        public string EmpNameEn { get; set; }
        public string FilePath { get; set; }
        public string EmpWorkId { get; set; }
        public int? NationalId { get; set; }

        public virtual TblItiPosition Pos { get; set; }
        public virtual ICollection<TblItiUser> TblItiUser { get; set; }
    }
}