// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiCategory
    {
        public TblItiCategory()
        {
            TblItiBook = new HashSet<TblItiBook>();
        }

        public int CateId { get; set; }
        public string CateNameKh { get; set; }
        public string CateNameEn { get; set; }

        public virtual ICollection<TblItiBook> TblItiBook { get; set; }
    }
}