// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiReadDetails
    {
        public TblItiReadDetails()
        {
            TblItiReturnReadDetails = new HashSet<TblItiReturnReadDetails>();
        }

        public int ReadDelId { get; set; }
        public int? ReadId { get; set; }
        public string BookDelId { get; set; }
        public int? StatusId { get; set; }

        public virtual TblItiBookdetails BookDel { get; set; }
        public virtual TblItiRead Read { get; set; }
        public virtual TblItiStatus Status { get; set; }
        public virtual ICollection<TblItiReturnReadDetails> TblItiReturnReadDetails { get; set; }
    }
}