// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiImportDetails
    {
        public int ImpDelId { get; set; }
        public int? ImpId { get; set; }
        public int? BookId { get; set; }
        public int? ImpQty { get; set; }
        public double? ImpPrice { get; set; }

        public virtual TblItiBook Book { get; set; }
        public virtual TblItiImport Imp { get; set; }
    }
}