// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ITI_Libraly_Api.Models
{
    public partial class TblItiBook
    {
        public TblItiBook()
        {
            TblItiBookdetails = new HashSet<TblItiBookdetails>();
            TblItiImportDetails = new HashSet<TblItiImportDetails>();
        }

        public int BookId { get; set; }
        public string BookNameKh { get; set; }
        public string BookNameEn { get; set; }
        public DateTime? BookYear { get; set; }
        public int? BookQty { get; set; }
        public int? CateId { get; set; }
        public string LocId { get; set; }
        public string FilePath { get; set; }
        public string BookDescription { get; set; }
        public string BookAuthor { get; set; }

        public virtual TblItiCategory Cate { get; set; }
        public virtual TblItiLocation Loc { get; set; }
        public virtual ICollection<TblItiBookdetails> TblItiBookdetails { get; set; }
        public virtual ICollection<TblItiImportDetails> TblItiImportDetails { get; set; }
    }
}